// Auto-generated by scripts/collect-portfolio-assets.sh — do not edit.
// Keys are project slugs; values are public URLs for next/image.

export const PORTFOLIO_ASSETS: Record<string, string> = {
  "andy": "/portfolio/andy/thumbnail.png",
};
