// Auto-generated by scripts/collect-portfolio-assets.sh — do not edit.
// Keys are project slugs; values describe thumbnail + screens for next/image.
//
// 보안 룰 (CLAUDE.md §5): src/ + public/ 에 금지 단어 절대 노출 X.
// 파일명 검사 후 cp 되었으며, scripts/check-security.sh 로 자가 검증됨.

export type PortfolioAsset = {
  thumbnail?: string;
  screens?: string[];
};

export const PORTFOLIO_ASSETS: Record<string, PortfolioAsset> = {
  "ttoktok": {
    thumbnail: "/portfolio/ttoktok/thumbnail.png",
  },
  "king-of-law": {
    thumbnail: "/portfolio/king-of-law/thumbnail.svg",
    screens: ["/portfolio/king-of-law/screen-1.svg"],
  },
  "andy": {
    thumbnail: "/portfolio/andy/thumbnail.png",
    screens: ["/portfolio/andy/screen-1.png", "/portfolio/andy/screen-2.png"],
  },
  "dev-safety": {
    thumbnail: "/portfolio/dev-safety/thumbnail.png",
  },
};
