#!/usr/bin/env bash
#
# 진주 ICT 사이트 — 포트폴리오 자산 자동 수집
#
# 각 프로젝트 폴더에서 스크린샷/로고/아이콘 자동 탐색 후
# public/portfolio/<slug>/thumbnail.<ext> 로 cp.
#
# 보안 룰:
#   - 파일명에 금지 단어 포함 시 skip
#   - cp 된 자산은 표준 이름 thumbnail.<ext> 로 통일 (원본 파일명 정보 누출 방지)
#
# 결과: src/lib/portfolio-assets.ts 자동 생성 (PortfolioCard 가 lookup)
#
# Note: macOS 기본 bash 3.2 호환 — associative array 사용 X.

set -e

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PUBLIC_DIR="$ROOT/public/portfolio"
MANIFEST="$ROOT/src/lib/portfolio-assets.ts"

mkdir -p "$PUBLIC_DIR"

# parallel arrays — index 매칭으로 slug ↔ source path
SLUGS=(
  "ttoktok"
  "shortdub"
  "king-of-law"
  "andy"
  "office-agent"
  "ai-news-daily"
  "dev-harness"
  "dev-safety"
)
# SKIP_SECURITY 마커: 보안 룰상 외부 자산 수집 금지 (placeholder fallback).
#   - client 의 보안 우려 항목 (회사 자산 노출 위험)
#   - internal (사내 도구 자산은 OSS 원본 로고일 가능성)
# Andy 만 상호명 노출 허용 (대표님 명시) → 자산 cp 가능.
PATHS=(
  "/Users/goldenplanet/jinsup_space/TtokTtok"
  "/Users/goldenplanet/jinsup_ralph/shortdub"
  "/Users/goldenplanet/jinsup_ralph/king_of_law"
  "/Users/goldenplanet/jinsup_space/Andy"
  "SKIP_SECURITY"
  "SKIP_SECURITY"
  "SKIP_SECURITY"
  "SKIP_SECURITY"
)

FORBIDDEN='(골든플래닛|geoffrey|huntley|ralph wiggum|superpowers|nexora)'
CANDIDATE_DIRS=(
  "."
  "public"
  "assets"
  "images"
  "docs"
  "screenshots"
  "mobile/assets"
  "app/src/main/res/drawable"
  "app/src/main/res/mipmap-hdpi"
  "app/src/main/res/mipmap-xxhdpi"
  "app/src/main/res/mipmap-xxxhdpi"
)
IMAGE_PATTERNS=(
  "logo.svg"
  "logo.png"
  "icon.svg"
  "icon.png"
  "icon-512.png"
  "ic_launcher.png"
  "screenshot.png"
  "screenshot-1.png"
  "preview.png"
  "thumbnail.png"
  "hero.png"
  "image.png"
  "*.png"
  "*.jpg"
  "*.jpeg"
  "*.svg"
)

ENTRIES=""
found=0
skipped=0

for i in "${!SLUGS[@]}"; do
  slug="${SLUGS[$i]}"
  src="${PATHS[$i]}"
  echo "[$slug] $src"
  if [ "$src" = "SKIP_SECURITY" ]; then
    echo "  ⊘  skip (security rule — internal/client asset cannot be exposed)"
    skipped=$((skipped + 1))
    continue
  fi
  if [ ! -d "$src" ]; then
    echo "  ⚠️  source not found"
    skipped=$((skipped + 1))
    continue
  fi

  match=""
  for dir in "${CANDIDATE_DIRS[@]}"; do
    p="$src/$dir"
    [ -d "$p" ] || continue
    for pattern in "${IMAGE_PATTERNS[@]}"; do
      hit=$(find "$p" -maxdepth 2 -type f -iname "$pattern" 2>/dev/null \
        | grep -vi 'node_modules\|\.next\|build\|dist\|\.git' || true)
      if [ -z "$hit" ]; then
        continue
      fi
      while IFS= read -r f; do
        [ -z "$f" ] && continue
        bn=$(basename "$f" | tr '[:upper:]' '[:lower:]')
        if echo "$bn" | grep -E -i "$FORBIDDEN" > /dev/null; then
          echo "  ⊘  skip (filename violates security): $(basename "$f")"
          continue
        fi
        match="$f"
        break 3
      done <<< "$hit"
    done
  done

  if [ -z "$match" ]; then
    echo "  ⚠️  no asset found (placeholder will render)"
    skipped=$((skipped + 1))
    continue
  fi

  ext="${match##*.}"
  ext_lower=$(echo "$ext" | tr '[:upper:]' '[:lower:]')
  dest_dir="$PUBLIC_DIR/$slug"
  mkdir -p "$dest_dir"
  cp "$match" "$dest_dir/thumbnail.$ext_lower"
  echo "  ✓ $(basename "$match") -> /portfolio/$slug/thumbnail.$ext_lower"
  ENTRIES="$ENTRIES  \"$slug\": \"/portfolio/$slug/thumbnail.$ext_lower\","$'\n'
  found=$((found + 1))
done

# ---------- Generate manifest ----------
{
  echo "// Auto-generated by scripts/collect-portfolio-assets.sh — do not edit."
  echo "// Keys are project slugs; values are public URLs for next/image."
  echo ""
  echo "export const PORTFOLIO_ASSETS: Record<string, string> = {"
  printf "%s" "$ENTRIES"
  echo "};"
} > "$MANIFEST"

echo ""
echo "Manifest written: $MANIFEST"
echo "Result: found=$found, skipped=$skipped, total=${#SLUGS[@]}"
